baseURL = "ZacharySantamaria.github.io"
languageCode = "en-us"
title = "Zachary Santamaria's Blog"
DefaultContentLanguage = "en"
theme = "diary"
googleAnalytics = "UA-260898949-2"


  
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4  


[params]
subtitle = "Adventures in tech"
enableGitalk = false
enableGiscus = true
googleSearchCode = '059e534c6b55c4832'

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "My Blog" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 3

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1

[taxonomies]
   category = "categories"
   tag = "tags"

 